flowercam/config/routes.rb
Flowercam::Application.routes.draw do
	get "image/index"
	post "image/apply_filter" , :as=>:apply_filter

  root :to => "image#index"

end

flowercam/app/models/image.rb
class Image
	def self.apply_filter img, filter
		path = write_content_to_file img
		
		apply_filter_pr path,filter
		
		ImageResult.new(@name_old,@name_new)
	end
	
	private
	
	def self.write_content_to_file img
		content = img[:content].read
		file_ext = File.extname(img[:content].original_filename)
		
		uuid = UUID.new
		generated_uuid = uuid.generate
		@name_old = generated_uuid + file_ext
		@name_new = generated_uuid + "new" + file_ext
		
		path = Rails.root.to_s + "/public/images/" 
		
		@old_image_fullpath = path + generated_uuid + file_ext
		
		File.open(@old_image_fullpath,"w") do |f|
			f.write(content.force_encoding("UTF-8"))
		end 		
		
		path
	end
	
	def self.apply_filter_pr path,filter
		new_image_fullpath = path + @name_new
		
		img = Magick::Image.read(@old_image_fullpath).first
		result = apply_filter_to_image img, filter
		result.write(new_image_fullpath)
	end
	
	def self.apply_filter_to_image img, filter
	 case filter
		when "posterize"  then img.posterize
		when "sepiatone"  then img.sepiatone
	 	when "shade"  then img.shade
	 	when "sharpen"  then img.sharpen
	 	when "sketch"  then img.sketch
	 	when "solarize"  then img.solarize
	 	when "vignette" then img.vignette
	 	when "wave" then img.wave
	 	when "wet_floor" then img.wet_floor
	 end
	
	end
end

flowercam/app/models/image_result.rb
class ImageResult
	attr_reader :old_name, :new_name
	
	def initialize old, new
		@old_name = old
		@new_name = new
	end
end

flowercam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

flowercam/app/controllers/image_controller.rb
require 'RMagick'

class ImageController < ApplicationController

	def index
	end
	
	def apply_filter
		if params[:file_content] && params[:filter]
			img_res = Image.apply_filter(params[:file_content],params[:filter])
			@name_new = img_res.new_name
			@name_old = img_res.old_name
		else
			flash[:alert] = "You have to choose image and filter!"
			render :action=>"index"
		end
	end
end

flowercam/app/helpers/application_helper.rb
module ApplicationHelper
end

flowercam/app/helpers/image_helper.rb
module ImageHelper
	def filters_array
		["posterize","sepiatone","shade","sharpen","sketch","solarize","vignette","wave","wet_floor"]
	end
end

flowercam/app/views/image/apply_filter.html.erb
<div>
	<%= image_tag @name_new%>
</div>

<div>
	<%= image_tag @name_old%>
</div>

flowercam/app/views/image/index.html.erb
    <div id="mainDiv">
        <%= image_tag 'dropHere.png',:id=>"imgBG", :style=>"border:1px solid #000;" %>
    </div>
    <div>
				<%= image_tag 'rotate_cw.png',:onclick=>"RotatePlus()" %>
        <%= image_tag 'rotate_ccw.png',:onclick=>"RotateMinus()" %>
    </div>
    
<%= form_tag (apply_filter_path),:multipart => true, :html => { :id => "certificate_update_form" } do %>
   	<%= file_field 'file_content', 'content'%>
   	<%= label_tag :filter%>
   	<%= select_tag :filter, options_for_select(filters_array)%><li>
		<%= submit_tag "Upload" %>
<% end %>


        <script>
        var dropbox = document.getElementById('imgBG');
        var mainDiv = document.getElementById('mainDiv');
        var Filters = {};
        arr = [];
        
        //dropbox.style.height = "500px";
        // Setup drag and drop handlers. 
        dropbox.addEventListener('dragenter', stopDefault, false);
        dropbox.addEventListener('dragover', stopDefault, false);
        dropbox.addEventListener('dragleave', stopDefault, false);
        dropbox.addEventListener('drop', onDrop, false);

        function stopDefault(e) {
            e.stopPropagation();
            e.preventDefault();
        }


        function onDrop(e) {
            e.stopPropagation();
            e.preventDefault();

            var readFileSize = 0;
            var files = e.dataTransfer.files;


            file = files[0];
            readFileSize += file.fileSize;


            // Only process image files. 
            var imageType = /image.*/;

            if (!file.type.match(imageType)) {
                return;
            }


            var reader = new FileReader();


            reader.onerror = function (e) {
                alert('Error code: ' + e.target.error);
            };


            // Create a closure to capture the file information. 
            reader.onload = (function (aFile) {
                return function (evt) {
                    dropbox.src = evt.target.result;
                    dropbox.style.height = "300px";
                    Filters.dropbox = dropbox;
                    Generate();                  
                }
            })(file);

            // Read in the image file as a data url. 
            reader.readAsDataURL(file);

        }

        var Rad = 0;
        function RotatePlus() {
            Rad += 90;
            document.getElementById("imgBG").style.webkitTransform = "rotate(" + Rad + "deg)"; // for Chrome
            document.getElementById("imgBG").style.MozTransform = "rotate(" + Rad + "deg)"; // for FF
            Filters.Invert.style.webkitTransform = "rotate(" + Rad + "deg)"; // for Chrome
            Filters.Invert.style.MozTransform = "rotate(" + Rad + "deg)"; // for FF
        }
        function RotateMinus() {
            Rad -= 90;
            document.getElementById("imgBG").style.webkitTransform = "rotate(" + Rad + "deg)"; // for Chrome
            document.getElementById("imgBG").style.MozTransform = "rotate(" + Rad + "deg)"; // for FF
            Filters.Invert.style.webkitTransform = "rotate(" + Rad + "deg)"; // for Chrome
            Filters.Invert.style.MozTransform = "rotate(" + Rad + "deg)"; // for FF
        }
     </script>

flowercam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flowercam</title>
  <%= stylesheet_link_tag :all %>
  
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>